
-- =========================================================
-- Growth Buddy — Database Schema
-- MySQL 8.0+
--
-- One collation throughout (utf8mb4_unicode_ci, matching the database default).
-- Mixing it with utf8mb4_0900_ai_ci made every cross-table join on a char(36)
-- id fail outright with "Illegal mix of collations" — invisible for as long as
-- the code looked rows up one id at a time from Java, fatal the moment a query
-- joined two tables.
--
-- UUIDs are stored as CHAR(36) text, matching what Hibernate actually
-- creates (application.yml sets preferred_uuid_jdbc_type: CHAR). This file
-- previously declared BINARY(16)/UUID_TO_BIN, which the app never used —
-- a prod deploy with SPRING_JPA_DDL_AUTO=validate would have failed.
-- IDs are generated by the app, so columns carry no DB-side default.
-- =========================================================

-- Use utf8mb4 across the board for emoji + full Unicode support.
-- Run this DB-creation line yourself if needed:
CREATE DATABASE growth_buddy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE growth_buddy;

-- =========================================================
-- USERS
-- =========================================================
CREATE TABLE users (
  id              CHAR(36)     NOT NULL,
  email           VARCHAR(254) NOT NULL,
  email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
  display_name    VARCHAR(120) NOT NULL,
  avatar_url      VARCHAR(255),
  timezone        VARCHAR(64)  NOT NULL DEFAULT 'UTC',
  dob             DATE         NULL,
  level           INT          NOT NULL DEFAULT 1,        -- cached XP level
  xp_total       INT          NOT NULL DEFAULT 0,        -- derived, cached
  digest_frequency VARCHAR(16) NOT NULL DEFAULT 'off',    -- off | daily | weekly progress digest
  digest_hour     INT          NOT NULL DEFAULT 8,        -- local hour (0-23) to send the digest
  last_digest_on  DATE         NULL,                      -- guards one digest per local day
  home_layout     JSON         NULL,                      -- ordered home widgets [{id,enabled}] (null = default)
  nav_layout      JSON         NULL,                      -- ordered bottom-nav [{id,primary}] (null = default)
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at      TIMESTAMP    NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE password_credentials (
  user_id          CHAR(36)     NOT NULL,
  password_hash    VARCHAR(255) NOT NULL,                 -- argon2id recommended
  algo             VARCHAR(32)  NOT NULL DEFAULT 'argon2id',
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_pw_creds_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sessions (
  id                  CHAR(36)     NOT NULL,
  user_id             CHAR(36)     NOT NULL,
  refresh_token_hash  VARCHAR(255) NOT NULL,              -- store hash, not the token
  user_agent          TEXT,
  ip                  VARCHAR(45),                        -- IPv4 or IPv6
  device_label        VARCHAR(120),
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at          TIMESTAMP    NOT NULL,
  revoked_at          TIMESTAMP    NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_session_refresh (refresh_token_hash),
  KEY ix_session_user_expires (user_id, expires_at),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE email_verification_tokens (
  token_hash       VARCHAR(255) NOT NULL,
  user_id          CHAR(36)     NOT NULL,
  expires_at       TIMESTAMP    NOT NULL,
  consumed_at      TIMESTAMP    NULL,
  PRIMARY KEY (token_hash),
  KEY ix_evt_user (user_id),
  CONSTRAINT fk_evt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_reset_tokens (
  token_hash       VARCHAR(255) NOT NULL,
  user_id          CHAR(36)     NOT NULL,
  expires_at       TIMESTAMP    NOT NULL,
  consumed_at      TIMESTAMP    NULL,
  PRIMARY KEY (token_hash),
  KEY ix_prt_user (user_id),
  CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE tasks (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  title           VARCHAR(255) NOT NULL,
  notes           TEXT,
  priority        VARCHAR(8)  NOT NULL DEFAULT 'Medium',
  due_at          TIMESTAMP    NULL,
  done            BOOLEAN      NOT NULL DEFAULT FALSE,
  done_at         TIMESTAMP    NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at      TIMESTAMP    NULL,
  PRIMARY KEY (id),
  KEY ix_tasks_user_due (user_id, due_at),
  KEY ix_tasks_user_done (user_id, done),
  CONSTRAINT fk_tasks_user     FOREIGN KEY (user_id)     REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE task_completion_history (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  task_id         CHAR(36)     NOT NULL,
  changed_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority        ENUM('Low','Medium','High') NOT NULL,
  due_at          TIMESTAMP    NULL,
  PRIMARY KEY (id),
  KEY ix_task_hist_user_task_time (user_id, task_id, changed_at),
  CONSTRAINT fk_task_hist_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_hist_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- HABITS  (recurrence is a column on the habit itself)
-- =========================================================
CREATE TABLE habits (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  name            VARCHAR(120) NOT NULL,
  domain          ENUM('habit','fitness','study','journal') NOT NULL DEFAULT 'habit',
  icon            VARCHAR(64)  NOT NULL,
  cadence         ENUM('daily','weekly','custom') NOT NULL DEFAULT 'daily',
  target_per_week INT          NOT NULL DEFAULT 7,
  active          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at      TIMESTAMP    NULL,
  PRIMARY KEY (id),
  KEY ix_habits_user (user_id),
  CONSTRAINT fk_habits_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE habit_checkins (
  habit_id        CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  log_date        DATE         NOT NULL,                  -- in user's local TZ at write time
  done            BOOLEAN      NOT NULL DEFAULT TRUE,
  protected_day   BOOLEAN      NOT NULL DEFAULT FALSE,     -- rest/freeze day: bridges the streak gap
  note            TEXT,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (habit_id, log_date),
  KEY ix_habit_checkin_user_date (user_id, log_date),
  CONSTRAINT fk_habit_checkin_habit FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE,
  CONSTRAINT fk_habit_checkin_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE habit_streaks (
  habit_id        CHAR(36) NOT NULL,
  current_streak  INT      NOT NULL DEFAULT 0,
  longest_streak  INT      NOT NULL DEFAULT 0,
  last_done_on    DATE     NULL,
  PRIMARY KEY (habit_id),
  CONSTRAINT fk_habit_streak_habit FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One freeze token granted per ISO week (Monday-anchored), capped; spent to
-- protect a habit day (planned rest or rescue of a missed day).
CREATE TABLE streak_freeze_wallets (
  user_id     CHAR(36) NOT NULL,
  tokens      INT      NOT NULL DEFAULT 1,
  week_anchor DATE     NOT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_freeze_wallet_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- WATER TRACKER
-- =========================================================
CREATE TABLE water_goals (
  user_id         CHAR(36) NOT NULL,
  goal_ml         INT      NOT NULL DEFAULT 2000,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_water_goal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_water_goal_range CHECK (goal_ml BETWEEN 250 AND 10000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE water_entries (
  id              CHAR(36)    NOT NULL,
  user_id         CHAR(36)  NOT NULL,
  amount_ml       INT       NOT NULL,
  note            VARCHAR(255) NULL,
  logged_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  log_date        DATE      NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_water_entry_user_date (user_id, log_date),
  CONSTRAINT fk_water_entry_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_water_amount_range CHECK (amount_ml BETWEEN 1 AND 5000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- FOOD CALORIE TRACKER
-- =========================================================
CREATE TABLE food_entries (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  food_name       VARCHAR(255) NOT NULL,
  quantity_grams  INT          NOT NULL,
  meal_type       ENUM('home','hotel') NOT NULL DEFAULT 'home',
  kcal_estimated  INT          NOT NULL,
  kcal_per_100g   INT          NOT NULL,
  estimate_source VARCHAR(20)  NOT NULL,
  note            VARCHAR(255) NULL,
  logged_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  log_date        DATE         NOT NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_food_entry_user_date (user_id, log_date),
  CONSTRAINT fk_food_entry_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_food_qty_range CHECK (quantity_grams BETWEEN 10 AND 2000),
  CONSTRAINT ck_food_kcal_range CHECK (kcal_estimated BETWEEN 1 AND 5000),
  CONSTRAINT ck_food_kcal_100g_range CHECK (kcal_per_100g BETWEEN 40 AND 900)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Recent food-photo analyses (the "recent scans" list); capped to 12 per user
-- on read.
CREATE TABLE food_photo_logs (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  log_date        DATE         NOT NULL,
  food_name       VARCHAR(255) NOT NULL,
  meal_type       VARCHAR(32)  NULL,
  confidence      INT          NULL,
  fallback_needed BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_food_photo_user_time (user_id, created_at),
  CONSTRAINT fk_food_photo_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- GOALS
-- =========================================================
CREATE TABLE goals (
  id              CHAR(36)   NOT NULL,
  user_id         CHAR(36)   NOT NULL,
  title           VARCHAR(255) NOT NULL,
  description     VARCHAR(1000),
  horizon         ENUM('short_term','mid_term','long_term') NOT NULL DEFAULT 'short_term',
  target_date     DATE         NULL,
  completed       BOOLEAN      NOT NULL DEFAULT FALSE,
  completed_at    TIMESTAMP    NULL,
  progress_json   TEXT         NULL,   -- opaque frontend progress blob (milestones, day-tracker)
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_goal_user_horizon (user_id, horizon),
  KEY ix_goal_user_completed (user_id, completed),
  CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE goal_actions (
  id              CHAR(36)   NOT NULL,
  goal_id         CHAR(36)   NOT NULL,
  user_id         CHAR(36)   NOT NULL,
  note            VARCHAR(1000) NOT NULL,
  action_date     DATE         NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_goal_action_goal_time (goal_id, created_at),
  KEY ix_goal_action_user_time (user_id, created_at),
  CONSTRAINT fk_goal_action_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
  CONSTRAINT fk_goal_action_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;





-- =========================================================
-- DAILY SCORE
-- =========================================================
CREATE TABLE daily_scores (
  user_id         CHAR(36) NOT NULL,
  score_date      DATE     NOT NULL,
  score           INT      NOT NULL,
  tasks_done      INT      NOT NULL DEFAULT 0,
  tasks_total     INT      NOT NULL DEFAULT 0,
  habits_done     INT      NOT NULL DEFAULT 0,
  habits_total    INT      NOT NULL DEFAULT 0,
  workout_done    BOOLEAN  NOT NULL DEFAULT FALSE,
  PRIMARY KEY (user_id, score_date),
  CONSTRAINT fk_daily_score_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_daily_score_range CHECK (score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-day wellness check-ins (sleep + mood) and a snapshot of headline metrics
-- (score / water / calories). Backs the Report trends + insights engine; every
-- column is nullable so a row may hold any subset.
CREATE TABLE daily_logs (
  user_id        CHAR(36) NOT NULL,
  log_date       DATE     NOT NULL,
  bedtime        VARCHAR(5),
  wake_time      VARCHAR(5),
  sleep_quality  VARCHAR(16),
  sleep_note     TEXT,
  mood           VARCHAR(16),
  energy         VARCHAR(16),
  stress         VARCHAR(16),
  mood_note      TEXT,
  score          INT,
  water_ml       INT,
  water_goal_ml  INT,
  kcal           INT,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, log_date),
  CONSTRAINT fk_daily_log_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- QUOTES
-- =========================================================
CREATE TABLE quotes (
  id              CHAR(36)     NOT NULL,
  body            TEXT         NOT NULL,
  author          VARCHAR(120) NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- MENTOR
-- =========================================================
CREATE TABLE mentor_threads (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  title           VARCHAR(255) NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_mentor_thread_user (user_id),
  CONSTRAINT fk_mentor_thread_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mentor_messages (
  id              CHAR(36)    NOT NULL,
  thread_id       CHAR(36)  NOT NULL,
  role            ENUM('user','assistant','system') NOT NULL,
  content         MEDIUMTEXT NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_mentor_msg_thread_time (thread_id, created_at),
  CONSTRAINT fk_mentor_msg_thread FOREIGN KEY (thread_id) REFERENCES mentor_threads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- GROWTH CIRCLES
-- =========================================================
CREATE TABLE circles (
  id              CHAR(36)     NOT NULL,
  name            VARCHAR(120) NOT NULL,
  goal            TEXT         NULL,
  created_by      CHAR(36)     NOT NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_circles_created_by (created_by),
  CONSTRAINT fk_circles_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE circle_members (
  circle_id       CHAR(36) NOT NULL,
  user_id         CHAR(36) NOT NULL,
  role            ENUM('owner','member') NOT NULL DEFAULT 'member',
  joined_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (circle_id, user_id),
  KEY ix_circle_member_user (user_id),
  CONSTRAINT fk_circle_member_circle FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE,
  CONSTRAINT fk_circle_member_user   FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE circle_posts (
  id              CHAR(36)    NOT NULL,
  circle_id       CHAR(36)  NOT NULL,
  user_id         CHAR(36)  NOT NULL,
  body            TEXT      NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_circle_post_circle_time (circle_id, created_at DESC),
  KEY ix_circle_post_user (user_id),
  CONSTRAINT fk_circle_post_circle FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE,
  CONSTRAINT fk_circle_post_user   FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Time-boxed habit challenges for a circle; members are ranked by check-ins
-- completed during [start_date, end_date].
CREATE TABLE circle_challenges (
  id              CHAR(36)    NOT NULL,
  circle_id       CHAR(36)  NOT NULL,
  title           VARCHAR(120) NOT NULL,
  start_date      DATE      NOT NULL,
  end_date        DATE      NOT NULL,
  created_by      CHAR(36)  NOT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_circle_challenge_circle (circle_id),
  CONSTRAINT fk_circle_challenge_circle FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE,
  CONSTRAINT fk_circle_challenge_user   FOREIGN KEY (created_by) REFERENCES users(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




-- =====================================================================
-- v2 additions: customisable habits, notifications bell, mentorship invites
-- =====================================================================

-- Habits customisation: per-habit color + time-of-day reminder.
-- These ALTERs are idempotent-ish: re-running them on a fresh schema is fine,
-- and on an already-migrated DB MySQL will error harmlessly (run via the
-- "Migrations" section below to apply just the missing parts).
--
-- ALTER TABLE habits
--   ADD COLUMN color VARCHAR(16) NULL AFTER icon,
--   ADD COLUMN reminder_time TIME NULL AFTER cadence;

-- Bell-style notifications. One row per item, with a "kind" so the UI
-- can format / route differently (e.g. mentorship requests show Accept/Reject).
CREATE TABLE IF NOT EXISTS notifications (
  id          CHAR(36)    NOT NULL,
  user_id     CHAR(36)  NOT NULL,
  kind        ENUM('mentorship_request','mentorship_accepted','mentorship_rejected','system') NOT NULL,
  title       VARCHAR(255) NOT NULL,
  body        TEXT          NULL,
  -- Optional pointer to whatever the notification is "about"
  -- (e.g. the mentorship_requests.id).
  related_id  CHAR(36)      NULL,
  read_at     TIMESTAMP     NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_notifications_user (user_id, read_at, created_at),
  CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Mentorship pairing requests.
--   direction = 'offer'   → from_user offers to mentor to_user
--   direction = 'request' → from_user asks to_user to be their mentor
-- The recipient sees a notification with Accept / Reject.
CREATE TABLE IF NOT EXISTS mentorship_requests (
  id            CHAR(36) NOT NULL,
  from_user_id  CHAR(36) NOT NULL,
  to_user_id    CHAR(36) NOT NULL,
  direction     ENUM('offer','request') NOT NULL,
  status        ENUM('pending','accepted','rejected','cancelled') NOT NULL DEFAULT 'pending',
  note          VARCHAR(500) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at  TIMESTAMP NULL,
  PRIMARY KEY (id),
  -- Don't put a unique key on (from, to, direction, status) — a 2nd
  -- accepted row legitimately shares that tuple once the pair has worked
  -- together twice. We enforce "one pending per direction" in code.
  KEY ix_mr_to_status   (to_user_id,   status, created_at),
  KEY ix_mr_from_status (from_user_id, status, created_at),
  CONSTRAINT fk_mr_from FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mr_to   FOREIGN KEY (to_user_id)   REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================================
-- Migrations (run once per environment that already has v1 schema).
-- Wrap each ALTER in its own statement so a re-run that errors on the
-- duplicate column doesn't abort the whole script.
-- =====================================================================

-- Habit customisation columns (v2)
ALTER TABLE habits ADD COLUMN color VARCHAR(16) NULL AFTER icon;
ALTER TABLE habits ADD COLUMN reminder_time TIME NULL AFTER cadence;

-- User profile & nutrition columns (v2)
-- These are auto-applied at startup by Hibernate ddl-auto: update,
-- but listed here for fresh installs and documentation.
ALTER TABLE users ADD COLUMN whatsapp_number  VARCHAR(20)    NULL;
ALTER TABLE users ADD COLUMN whatsapp_enabled BOOLEAN        NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN age_years        INT            NULL;
ALTER TABLE users ADD COLUMN height_cm        INT            NULL;
ALTER TABLE users ADD COLUMN weight_kg        DECIMAL(5,1)   NULL;
ALTER TABLE users ADD COLUMN diet_preference  VARCHAR(64)    NULL;
ALTER TABLE users ADD COLUMN about_me         VARCHAR(500)   NULL;
ALTER TABLE users ADD COLUMN daily_food_goal_kcal INT        NULL;
ALTER TABLE users ADD COLUMN daily_water_goal_ml  INT        NULL;
ALTER TABLE users ADD COLUMN gender               VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN fitness_goal         VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN whatsapp_verified    BOOLEAN NOT NULL DEFAULT FALSE;

-- Present in the entity and read in 24 places, but never in this file: a fresh
-- database built from it produced a users table the app could not query at all.
ALTER TABLE users ADD COLUMN favourite_dish   VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN allergic_to      VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN feature_prefs    JSON         NULL;
ALTER TABLE users ADD COLUMN ui_prefs         JSON         NULL;

-- nav_layout is declared in the users CREATE TABLE above, so it needs no ALTER
-- here: adding it twice made this file abort mid-load on a fresh database,
-- leaving 28 of 45 tables. Upgrading an older DB that predates the column?
-- Run the ALTER by hand, or let dev's ddl-auto: update add it.

CREATE TABLE IF NOT EXISTS whatsapp_otp_tokens (
  token_hash  VARCHAR(255) NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  phone       VARCHAR(20)  NOT NULL,
  expires_at  DATETIME(6)  NOT NULL,
  consumed_at DATETIME(6)  NULL,
  PRIMARY KEY (token_hash),
  KEY idx_wa_otp_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Drop stale unique index if it exists from an earlier schema version
-- ALTER TABLE mentorship_requests DROP INDEX uq_mr_pending;

-- =====================================================================
-- FAMILY (Family tab & AI South Indian meal planner) — v3
-- Auto-created at startup by Hibernate ddl-auto: update; listed here for
-- fresh installs and documentation. A household is a shared graph: multiple
-- accounts resolve into the same family via family_members.linked_user_id.
-- =====================================================================
CREATE TABLE IF NOT EXISTS families (
  id              CHAR(36)     NOT NULL,
  owner_user_id   CHAR(36)     NOT NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_family_owner (owner_user_id),
  CONSTRAINT fk_family_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS family_members (
  id                    CHAR(36)     NOT NULL,
  family_id             CHAR(36)     NOT NULL,
  linked_user_id        CHAR(36)     NULL,
  name                  VARCHAR(120) NOT NULL,
  relationship          VARCHAR(16)  NOT NULL DEFAULT 'other',
  dob                   DATE         NULL,
  gender                VARCHAR(20)  NULL,
  status                VARCHAR(12)  NOT NULL DEFAULT 'unmapped',
  favourite_dishes      TEXT         NULL,
  favourite_ingredients TEXT         NULL,
  diet_preference       VARCHAR(32)  NULL,
  allergies             TEXT         NULL,
  ingredients_to_avoid  TEXT         NULL,
  medical_conditions    TEXT         NULL,
  created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at            TIMESTAMP    NULL,
  PRIMARY KEY (id),
  KEY ix_family_member_family (family_id),
  KEY ix_family_member_linked (linked_user_id),
  CONSTRAINT fk_family_member_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
  CONSTRAINT fk_family_member_user FOREIGN KEY (linked_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS family_meal_plans (
  id                   CHAR(36)     NOT NULL,
  family_id            CHAR(36)     NOT NULL,
  plan_json            TEXT         NOT NULL,
  grocery_items_json   TEXT         NULL,
  generated_by_user_id CHAR(36)     NOT NULL,
  source               VARCHAR(24)  NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_family_meal_plan_family (family_id, created_at),
  CONSTRAINT fk_family_meal_plan_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Family invitations consent handshake (v3.1): a registered member starts as
-- 'invited' (pending) and must accept before joining the shared family.
-- ddl-auto: update will NOT widen an existing ENUM, so run this once.
ALTER TABLE family_members
  MODIFY COLUMN status ENUM('unmapped','invited','mapped') NOT NULL DEFAULT 'unmapped';

-- Family invite-only flag (v3.2): rows created solely to carry an invite are
-- removed (not orphaned) when the invitee declines. Run once.
ALTER TABLE family_members ADD COLUMN invite_only BOOLEAN NOT NULL DEFAULT FALSE AFTER status;

-- Family member physique (v3.3): height/weight for nutrition tailoring.
-- ddl-auto: update auto-adds these nullable columns; listed for fresh installs.
ALTER TABLE family_members ADD COLUMN height_cm INT NULL AFTER gender;
ALTER TABLE family_members ADD COLUMN weight_kg INT NULL AFTER height_cm;

-- =========================================================
-- MONEY BUDDY  (v4)
-- The whole money state (expenses, budgets, savings goals, custom tags,
-- challenges, wishlist, subscriptions, reflections, settings) is stored as one
-- per-user JSON document. All insights/health-score/search/etc. are computed
-- client-side, so there is no server-side query that would need normalized
-- tables. ddl-auto: update creates this automatically; listed for fresh installs.
-- =========================================================
CREATE TABLE money_state (
  user_id    CHAR(36)  NOT NULL,
  data       JSON      NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_money_state_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- TABLES CAPTURED FROM THE LIVE DB  (v6)
-- These were created by Hibernate ddl-auto and never written down here,
-- so a fresh install from this file was missing them (fatal under
-- SPRING_JPA_DDL_AUTO=validate). Pasted verbatim from SHOW CREATE TABLE,
-- which is why the style differs from the hand-written sections above:
-- ddl-auto emits no FK to users(id) and collates utf8mb4_unicode_ci.
-- Match a section above if you ever normalise them.
-- =========================================================
CREATE TABLE `calendar_reminders` (
  `id` char(36) NOT NULL,
  `anchor_date` date NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `from_date` date DEFAULT NULL,
  `repeat_freq` varchar(16) NOT NULL,
  `tag` varchar(16) NOT NULL,
  `text` varchar(255) NOT NULL,
  `time_of_day` time(6) DEFAULT NULL,
  `until_date` date DEFAULT NULL,
  `user_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_cal_rem_user_date` (`user_id`,`anchor_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `calendar_reminder_skips` (
  `reminder_id` char(36) NOT NULL,
  `skip_date` date NOT NULL,
  PRIMARY KEY (`reminder_id`,`skip_date`),
  CONSTRAINT `FK3fhfwht79vx2f490y2wxnsaeb` FOREIGN KEY (`reminder_id`) REFERENCES `calendar_reminders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `reminder_dispatch_log` (
  `id` char(36) NOT NULL,
  `channel` varchar(16) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `occurrence_date` date NOT NULL,
  `reminder_id` char(36) NOT NULL,
  `status` varchar(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_rem_dispatch_unique` (`reminder_id`,`occurrence_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `push_subscriptions` (
  `id` char(36) NOT NULL,
  `auth` varchar(255) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `endpoint` text NOT NULL,
  `p256dh` varchar(255) NOT NULL,
  `user_id` char(36) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `focus_sessions` (
  `id` char(36) NOT NULL,
  `completed_at` datetime(6) NOT NULL,
  `duration_sec` int NOT NULL,
  `mode` varchar(16) NOT NULL,
  `user_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_focus_user_time` (`user_id`,`completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `weekly_reviews` (
  `id` char(36) NOT NULL,
  `focus` varchar(255) DEFAULT NULL,
  `saved_at` datetime(6) NOT NULL,
  `user_id` char(36) NOT NULL,
  `week_start` date NOT NULL,
  `wins` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKkehyqqd8f9e6ogi8aqmd1s3xa` (`user_id`,`week_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `family_dish_preferences` (
  `id` char(36) NOT NULL,
  `dish_name` varchar(160) NOT NULL,
  `family_id` char(36) NOT NULL,
  `last_seen` datetime(6) NOT NULL,
  `score` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_family_dish` (`family_id`,`dish_name`),
  KEY `ix_family_dish_family` (`family_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `family_pantry_items` (
  `id` char(36) NOT NULL,
  `category` varchar(32) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `family_id` char(36) NOT NULL,
  `is_leftover` bit(1) NOT NULL,
  `name` varchar(120) NOT NULL,
  `quantity` varchar(60) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_family_pantry_family` (`family_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `family_shopping_items` (
  `id` char(36) NOT NULL,
  `checked` bit(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by_user_id` char(36) NOT NULL,
  `estimated_cost` int DEFAULT NULL,
  `family_id` char(36) NOT NULL,
  `name` varchar(120) NOT NULL,
  `quantity` varchar(60) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_family_shopping_family` (`family_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `family_favourite_menus` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by_user_id` char(36) NOT NULL,
  `family_id` char(36) NOT NULL,
  `name` varchar(120) NOT NULL,
  `occasion` varchar(16) DEFAULT NULL,
  `plan_json` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_family_fav_family` (`family_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `family_multi_day_plans` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `days` int NOT NULL,
  `family_id` char(36) NOT NULL,
  `generated_by_user_id` char(36) NOT NULL,
  `occasion` varchar(16) DEFAULT NULL,
  `plan_json` text NOT NULL,
  `source` varchar(24) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_family_multiday_family` (`family_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;
